import Head from "next/head";
import Link from "next/link";
import { FaSquareFacebook, FaSquareGithub, FaSquareInstagram, FaSquareXTwitter } from "react-icons/fa6";

export default function Home() {
  return (
    <>
      <Head>
        <title>Road to Perelman - €70,96 collected</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-purple-500">
        <div className="container flex flex-col items-center justify-center gap-16 px-4 py-16">
          <div className="flex flex-row gap-4 md:gap-8">
            <section className="flex flex-col gap-y-8 items-end justify-center pr-32 text-right">

              <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
                Road to <span className="text-white">Perelman</span>
              </h1>

              <input
                type="text"
                value="€1265,02"
                className="text-5xl sm:text-[5rem] font-bold text-right w-full  border-0 bg-black text-white rounded-3xl p-2 px-8"
              />

              <div className="text-xs">
                - or, in better words, roughly 126.502 unique signatures - collected since 10-10-2024.
                <br />
                €70,42 of which refunded.
                <br />
                View source code or follow my journey on:

                <div className="flex flex-row justify-end gap-2 text-[2rem] mt-4">
                  <FaSquareGithub />
                  <FaSquareXTwitter />
                  <FaSquareFacebook />
                  <FaSquareInstagram />
                </div>
              </div>
            </section>

            <div className="w-[1px] bg-black/10" />

            <section
              className="flex w-full flex-col gap-4 rounded-xl p-4 pl-32 text-black max-w-2xl"
            >
              <h3 className="text-2xl font-bold text-black">What is this..?</h3>
              <div className="text-3xl flex flex-col gap-8">
                <span>
                  Hi, what you&apos;re looking at is a simple man&apos;s journey to, hopefully, meeting a person named <h1 className="font-bold inline">Grigori Perelman</h1>.
                </span>

                <span className="block text-sm rounded-lg p-4 bg-black/10 text-black">
                  Grigori Perelman is arguably one of the mathematicians that has ever existed in the history of mankind.
                  As well as a <b>true</b> alchemist I proclaim.
                </span>

                <div className="block">
                  Help fulfill my dream simply by donating <strong>only €0.01</strong> once!
                </div>

                <div className="block text-sm rounded-lg p-4 bg-black/10 text-black">
                  <ul className="text-xs text-black border-black">
                    <li className="font-extrabold uppercase">Very important notice</li>
                    <li>- A donation can be made only <u>once</u> per person.</li>
                    <li>- It is only possible to donate the <u>fixed amount</u> of €0.01</li>
                    <li>- You may request a refund within 7 years of your donation.</li>
                  </ul>
                </div>

                <div className="grid grid-cols-1 gap-2">
                  <Link href="https://buymeacoffee.com/roadtoperelman" className="bg-black text-white rounded-lg p-4 text-sm font-bold flex items-center justify-center">
                    Buy me a thumbs up 👍
                  </Link>
                  <button className="bg-transparent text-black rounded-lg p-4 text-sm font-bold block">
                    Request refund
                  </button>
                </div>
              </div>
            </section>
          </div>
        </div>
      </main>
    </>
  );
}
